FROM python:3.10.4-alpine3.15

WORKDIR /app
COPY ./app.py .
COPY ./engine.py .
COPY ./requirements.txt .

RUN pip install -r requirements.txt

# CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=5001"]
# ENTRYPOINT [ "python" ]

